// ajax and loading actions
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// Auth actions
export const AUTH_INITIALIZATION_DONE = 'AUTH_INITIALIZATION_DONE';
export const AUTH_LOGGED_IN_SUCCESS = 'AUTH_LOGGED_IN_SUCCESS';
export const AUTH_LOGGED_OUT_SUCCESS = 'AUTH_LOGGED_OUT_SUCCESS';

// User actions
export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_IS_ADMIN_SUCCESS = 'USER_IS_ADMIN_SUCCESS';

// Room actions
export const ROOM_CREATED_SUCCESS = 'ROOM_CREATED_SUCCESS';
export const ROOM_LOADED_SUCCESS = 'ROOM_LOADED_SUCCESS';
export const ROOM_HAS_BEEN_CREATED = 'ROOM_HAS_BEEN_CREATED';
export const ROOM_HAS_BEEN_DELETED = 'ROOM_HAS_BEEN_DELETED';
export const ROOM_JOINED_SUCCESS = 'ROOM_JOINED_SUCCESS';
export const ROOMS_PURGE_LIST = 'ROOMS_PURGE_LIST';

// Message actions
export const MESSAGE_SENT_SUCCESS = 'MESSAGE_SENT_SUCCESS';
export const MESSAGE_RECEIVED_SUCCESS = 'MESSAGE_RECEIVED_SUCCESS';
export const MESSAGES_PURGE_PREVIOUS = 'MESSAGES_PURGE_PREVIOUS';